/** Numerical reality is stored here; agent beliefs and intentions are separate. */
export type EventCategory = 'Political' | 'Military' | 'Economic' | 'Religious' | 'Scientific' | 'Technological' | 'Cultural' | 'Environmental' | 'Biological' | 'Demographic' | 'Diplomatic' | 'Criminal' | 'Personal' | 'Disaster' | 'Exploration' | 'Cosmic';
export interface StateChange { entityId: string; field: string; before: unknown; after: unknown }
export interface HistoryEvent { id: string; timestamp: number; year: number; day: number; category: EventCategory; severity: 1 | 2 | 3 | 4 | 5; location: string; actors: string[]; factions: string[]; title: string; description: string; causes: string[]; effects: string[]; stateChanges: StateChange[]; relatedEvents: string[]; visibility: 'public' | 'private' | 'rumor'; tags: string[] }
export interface Knowledge { id: string; topic: string; belief: string; actual?: number; perceived?: number; confidence: number; source: string; eventId?: string; learnedYear: number; isRumor: boolean }
export interface Memory { eventId: string; year: number; description: string; emotion: string }
export interface Relationship { characterId: string; type: string; affection: number; trust: number; fear: number; respect: number; resentment: number; loyalty: number }
export interface DecisionOption { action: string; label: string; preference: 'High' | 'Moderate' | 'Low'; score: number; reason: string }
export interface Intention { action: string; target: string; intensity: number; reason: string; knowledgeIds: string[]; considered: DecisionOption[]; year: number; executed: boolean }
export interface Character { id: string; name: string; civId: string; role: string; age: number; alive: boolean; traits: Record<string, number>; goals: string[]; beliefs: string[]; fears: string[]; knowledge: Knowledge[]; memories: Memory[]; relationships: Relationship[]; thoughts: string[]; plans: Intention[]; health: number; influence: number; wealth: number; deathYear?: number; bornYear: number; sex: string; culture: string; socialClass: string; dynasty?: string; publicPosition: string; skills: Record<string, number>; secrets: string[]; tags: string[]; attributes: Record<string, unknown> }
export interface SocialGroup { id: string; name: string; share: number; influence: number; happiness: number; wealth: number; ideology: string; goals: string[] }
export interface Resource { name: string; stock: number; production: number; demand: number; price: number }
export interface Culture { language: string; values: string[]; customs: string[]; architecture: string; cuisine: string; traditions: string[] }
export interface CivilRelation { civId: string; trust: number; trade: number; grievance: number; alliance: boolean }
export interface Disease { id: string; name: string; infected: number; fatality: number; transmissibility: number; immunity: number; startedYear: number; causeEventId: string; deaths: number }
export interface Civilization { id: string; name: string; color: string; population: number; government: string; capital: string; leaderId: string; religionId: string; territory: number; food: number; treasury: number; taxRate: number; happiness: number; stability: number; military: number; technologies: string[]; research: number; resources: Resource[]; culture: Culture; groups: SocialGroup[]; relations: CivilRelation[]; dynasty: string; succession: string[]; debt: number; literacy: number; climate: number; soil: number; disease?: Disease; active: boolean; collapsedYear?: number; attributes: Record<string, unknown> }
export interface Religion { id: string; name: string; origin: string; deity: string; doctrines: string[]; rituals: string[]; holyText: string; clergy: string; followers: number; influence: number; denominations: string[]; parentId?: string; foundedYear: number; tags: string[] }
export interface War { id: string; name: string; attackerId: string; defenderId: string; participants: string[]; cause: string; causeEventId: string; goals: string[]; startedYear: number; endedYear?: number; active: boolean; casualties: number; battles: string[]; morale: Record<string, number>; winnerId?: string; commanderIds: string[]; logistics: Record<string, number> }
export interface CanonItem { id: string; description: string; year: number; origin: 'creation' | 'intervention' | 'emergent'; facts: string[]; disputedFacts: string[]; entityIds: string[]; tags: string[]; attributes?: Record<string, unknown> }
export interface MapCell { x: number; y: number; elevation: number; biome: 'ocean' | 'plains' | 'forest' | 'mountains' | 'desert' | 'river'; civId?: string; resource?: string }
export interface Settlement { id: string; name: string; x: number; y: number; civId: string; population: number }
export interface Geography { width: number; height: number; cells: MapCell[]; settlements: Settlement[]; seed: string }
export interface PopulationPoint { year: number; population: number; civilizations: Record<string, number> }
export interface World { version: 1; id: string; name: string; seed: string; origin: string; unusual: string; year: number; day: number; era: string; createdAt: string; updatedAt: string; civilizations: Civilization[]; characters: Character[]; religions: Religion[]; wars: War[]; events: HistoryEvent[]; canon: CanonItem[]; geography: Geography; populationHistory: PopulationPoint[]; rngState: number; nextEntity: number; tick: number; attributes: Record<string, unknown> }
export interface CreateWorldInput { name?: string; seed?: string | number; origin?: string; unusual?: string; scenario?: string }
export interface AdvanceSummary { fromYear: number; toYear: number; duration: string; steps: number; events: HistoryEvent[]; eventCount: number; stoppedReason?: string }
export interface AdvanceResult { world: World; summary: AdvanceSummary }
export interface ParsedTime { years: number; label: string; until?: 'ruler-death' | 'war-end' | 'exploration' | 'major-event' | 'war' | 'collapse' | 'religion' | 'technology' | 'plague' }
export interface InterventionOperation { type: string; targetId?: string; value?: number | string; details?: Record<string, unknown> }
export interface InterventionProposal { id: string; text: string; action: string; location: string; targets: string[]; immediateEffects: string[]; assumptions: string[]; destructive: boolean; operations: InterventionOperation[]; worldId: string; year: number }
export interface WorldAnswer { answer: string; sources: string[]; mode: 'local'; facts: string[] }
export interface TechnologyDefinition { name: string; prerequisites: string[]; category: string; cost: number; impact: string }
